--
-- PostgreSQL database dump
--

-- Dumped from database version 17.4
-- Dumped by pg_dump version 17.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.categories (
    id bigint NOT NULL,
    item_type character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    CONSTRAINT categories_item_type_check CHECK (((item_type)::text = ANY ((ARRAY['FOOD'::character varying, 'DRINK'::character varying, 'MERCHANDISE'::character varying])::text[])))
);


ALTER TABLE public.categories OWNER TO postgres;

--
-- Name: categories_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.categories_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customers; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.customers (
    id bigint NOT NULL,
    date_of_birth date,
    email character varying(255),
    first_name character varying(255),
    is_member boolean NOT NULL,
    last_name character varying(255),
    member_id character varying(5),
    phone character varying(255)
);


ALTER TABLE public.customers OWNER TO postgres;

--
-- Name: customers_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.customers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customization_options; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.customization_options (
    id bigint NOT NULL,
    additional_price double precision NOT NULL,
    name character varying(255) NOT NULL,
    customization_id bigint NOT NULL
);


ALTER TABLE public.customization_options OWNER TO postgres;

--
-- Name: customization_options_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.customization_options ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customization_options_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: customizations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.customizations (
    id bigint NOT NULL,
    name character varying(255) NOT NULL
);


ALTER TABLE public.customizations OWNER TO postgres;

--
-- Name: customizations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.customizations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.customizations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: item_customizations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.item_customizations (
    id bigint NOT NULL,
    customization_id bigint NOT NULL,
    item_code character varying(11) NOT NULL
);


ALTER TABLE public.item_customizations OWNER TO postgres;

--
-- Name: item_customizations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.item_customizations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.item_customizations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: item_sizes; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.item_sizes (
    id bigint NOT NULL,
    price double precision NOT NULL,
    size character varying(255) NOT NULL,
    item_code character varying(11) NOT NULL
);


ALTER TABLE public.item_sizes OWNER TO postgres;

--
-- Name: item_sizes_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.item_sizes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.item_sizes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.items (
    dtype character varying(31) NOT NULL,
    item_code character varying(11) NOT NULL,
    base_price double precision NOT NULL,
    name character varying(255) NOT NULL,
    category_id bigint NOT NULL
);


ALTER TABLE public.items OWNER TO postgres;

--
-- Name: transaction_item_customizations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.transaction_item_customizations (
    id bigint NOT NULL,
    customization_option_id bigint NOT NULL,
    transaction_item_id bigint NOT NULL
);


ALTER TABLE public.transaction_item_customizations OWNER TO postgres;

--
-- Name: transaction_item_customizations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.transaction_item_customizations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transaction_item_customizations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transaction_items; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.transaction_items (
    id bigint NOT NULL,
    price double precision NOT NULL,
    quantity integer NOT NULL,
    size character varying(255),
    item_code character varying(11) NOT NULL,
    transaction_id bigint NOT NULL
);


ALTER TABLE public.transaction_items OWNER TO postgres;

--
-- Name: transaction_items_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.transaction_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transaction_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transactions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.transactions (
    id bigint NOT NULL,
    total double precision NOT NULL,
    transaction_date timestamp(6) without time zone NOT NULL,
    cashier_id bigint,
    customer_id bigint
);


ALTER TABLE public.transactions OWNER TO postgres;

--
-- Name: transactions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    username character varying(255) NOT NULL,
    enabled boolean NOT NULL,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['ADMIN'::character varying, 'MANAGER'::character varying, 'CASHIER'::character varying])::text[])))
);


ALTER TABLE public.users OWNER TO postgres;

--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: categories; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.categories (id, item_type, name) FROM stdin;
\.


--
-- Data for Name: customers; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.customers (id, date_of_birth, email, first_name, is_member, last_name, member_id, phone) FROM stdin;
\.


--
-- Data for Name: customization_options; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.customization_options (id, additional_price, name, customization_id) FROM stdin;
\.


--
-- Data for Name: customizations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.customizations (id, name) FROM stdin;
\.


--
-- Data for Name: item_customizations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.item_customizations (id, customization_id, item_code) FROM stdin;
\.


--
-- Data for Name: item_sizes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.item_sizes (id, price, size, item_code) FROM stdin;
\.


--
-- Data for Name: items; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.items (dtype, item_code, base_price, name, category_id) FROM stdin;
\.


--
-- Data for Name: transaction_item_customizations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.transaction_item_customizations (id, customization_option_id, transaction_item_id) FROM stdin;
\.


--
-- Data for Name: transaction_items; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.transaction_items (id, price, quantity, size, item_code, transaction_id) FROM stdin;
\.


--
-- Data for Name: transactions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.transactions (id, total, transaction_date, cashier_id, customer_id) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, password, role, username, enabled) FROM stdin;
1	Cashier1	CASHIER	cashier1	t
7	cashier8	CASHIER	Cashier8	t
9	cashier9	CASHIER	Cashier9	t
10	apitlog	MANAGER	apit	t
\.


--
-- Name: categories_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.categories_id_seq', 1, false);


--
-- Name: customers_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.customers_id_seq', 1, false);


--
-- Name: customization_options_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.customization_options_id_seq', 1, false);


--
-- Name: customizations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.customizations_id_seq', 1, false);


--
-- Name: item_customizations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.item_customizations_id_seq', 1, false);


--
-- Name: item_sizes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.item_sizes_id_seq', 1, false);


--
-- Name: transaction_item_customizations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.transaction_item_customizations_id_seq', 1, false);


--
-- Name: transaction_items_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.transaction_items_id_seq', 1, false);


--
-- Name: transactions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.transactions_id_seq', 1, false);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 10, true);


--
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- Name: customers customers_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT customers_pkey PRIMARY KEY (id);


--
-- Name: customization_options customization_options_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customization_options
    ADD CONSTRAINT customization_options_pkey PRIMARY KEY (id);


--
-- Name: customizations customizations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customizations
    ADD CONSTRAINT customizations_pkey PRIMARY KEY (id);


--
-- Name: item_customizations item_customizations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.item_customizations
    ADD CONSTRAINT item_customizations_pkey PRIMARY KEY (id);


--
-- Name: item_sizes item_sizes_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.item_sizes
    ADD CONSTRAINT item_sizes_pkey PRIMARY KEY (id);


--
-- Name: items items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.items
    ADD CONSTRAINT items_pkey PRIMARY KEY (item_code);


--
-- Name: transaction_item_customizations transaction_item_customizations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transaction_item_customizations
    ADD CONSTRAINT transaction_item_customizations_pkey PRIMARY KEY (id);


--
-- Name: transaction_items transaction_items_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transaction_items
    ADD CONSTRAINT transaction_items_pkey PRIMARY KEY (id);


--
-- Name: transactions transactions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT transactions_pkey PRIMARY KEY (id);


--
-- Name: customers ukdehscjth39bn1tqvdql70xuex; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customers
    ADD CONSTRAINT ukdehscjth39bn1tqvdql70xuex UNIQUE (member_id);


--
-- Name: users ukr43af9ap4edm43mmtq01oddj6; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT ukr43af9ap4edm43mmtq01oddj6 UNIQUE (username);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: item_sizes fk2mrhewyd2ubsotfxgp4aw0oog; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.item_sizes
    ADD CONSTRAINT fk2mrhewyd2ubsotfxgp4aw0oog FOREIGN KEY (item_code) REFERENCES public.items(item_code);


--
-- Name: transaction_items fk2tx6lnc2j1wd1235lms8qj35c; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transaction_items
    ADD CONSTRAINT fk2tx6lnc2j1wd1235lms8qj35c FOREIGN KEY (item_code) REFERENCES public.items(item_code);


--
-- Name: item_customizations fk6eb5wfd7nrxrvhymki6j7ulut; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.item_customizations
    ADD CONSTRAINT fk6eb5wfd7nrxrvhymki6j7ulut FOREIGN KEY (customization_id) REFERENCES public.customizations(id);


--
-- Name: transaction_item_customizations fk74bnc0di1py8cgpdkjdrrm8yy; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transaction_item_customizations
    ADD CONSTRAINT fk74bnc0di1py8cgpdkjdrrm8yy FOREIGN KEY (transaction_item_id) REFERENCES public.transaction_items(id);


--
-- Name: transaction_item_customizations fkagfooui3pfp3ylcq58klhpamp; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transaction_item_customizations
    ADD CONSTRAINT fkagfooui3pfp3ylcq58klhpamp FOREIGN KEY (customization_option_id) REFERENCES public.customization_options(id);


--
-- Name: customization_options fkc25ytr9yhjxqmrrvvp7h3rp6i; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.customization_options
    ADD CONSTRAINT fkc25ytr9yhjxqmrrvvp7h3rp6i FOREIGN KEY (customization_id) REFERENCES public.customizations(id);


--
-- Name: transaction_items fkfaqqkmi2ahnahay1ciwffqwyp; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transaction_items
    ADD CONSTRAINT fkfaqqkmi2ahnahay1ciwffqwyp FOREIGN KEY (transaction_id) REFERENCES public.transactions(id);


--
-- Name: items fkjcdcde7htb3tyjgouo4g9xbmr; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.items
    ADD CONSTRAINT fkjcdcde7htb3tyjgouo4g9xbmr FOREIGN KEY (category_id) REFERENCES public.categories(id);


--
-- Name: transactions fkld32c0oc871tmae0dse406qv; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT fkld32c0oc871tmae0dse406qv FOREIGN KEY (cashier_id) REFERENCES public.users(id);


--
-- Name: item_customizations fkm6chtk96kanmiij2vh296mjeu; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.item_customizations
    ADD CONSTRAINT fkm6chtk96kanmiij2vh296mjeu FOREIGN KEY (item_code) REFERENCES public.items(item_code);


--
-- Name: transactions fkpnnreq9lpejqyjfct60v7n7x1; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transactions
    ADD CONSTRAINT fkpnnreq9lpejqyjfct60v7n7x1 FOREIGN KEY (customer_id) REFERENCES public.customers(id);


--
-- PostgreSQL database dump complete
--

