# Generated by Django 5.2 on 2025-05-12 03:59

import ECommerce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECommerce', '0002_remove_product_id_alter_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_date',
            field=models.DateTimeField(default=ECommerce.models.random_delivery_time),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
