# Generated by Django 5.2.1 on 2025-05-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ECommerce', '0004_orderitem_product_name_orderitem_product_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
